#!/bin/bash

frame_parameters() {
    if [[ -n "${NORV-}" ]]; then
	echo ""
    else
	echo '--frame-parameters="((reverse . t))"'
    fi
}

ssh -f -A -Y spicy /usr/local/bin/emacsclient \
    --alternate-editor='' \
    --create-frame \
    $(frame_parameters) \
    "$@"
