#!/usr/bin/env bash

ssh -f -A -Y spicy emacsclient \
    --alternate-editor='' \
    --create-frame \
    --frame-parameters='"((reverse . t))"' \
    "$@"

# ssh -f -A -Y spicy env XAUTHORITY=/run/user/1000/gdm/Xauthority emacsclient \
#     --alternate-editor='' \
#     --create-frame \
#     --frame-parameters='"((reverse . t))"' \
#     "$@"
