#!/usr/bin/env bash

frame_parameters() {
    if [[ -n "${NORV-}" ]]; then
	echo ""
    else
	echo '--frame-parameters="((background-color . \"white\") (foreground-color . \"black\"))"'
    fi
}

ssh -f -X -A -Y ${REMOTE_HOST:-spicy} emacsclient \
    --alternate-editor='' \
    --create-frame \
    $(frame_parameters) \
    "$@"

# ssh -f -A -Y spicy /usr/local/bin/emacsclient \
#     --alternate-editor='' \
#     --create-frame \
#     $(frame_parameters) \
#     "$@"
